import { useAuth } from '../hooks/useAuth';
import { useUI } from '../hooks/useUI';
import Sheet from './Sheet';

/**
 * What is stored, where, and what leaves the device.
 *
 * Written because the app now keeps testers' email addresses on a server and said nothing about
 * it anywhere. Every line here is checkable against the code — the point is to be accurate rather
 * than reassuring, and where the honest answer is "yes, that goes elsewhere", it says so and names
 * who receives it.
 *
 * Deliberately not a legal privacy policy. This is a small app used by a handful of people, and a
 * page of boilerplate about "affiliates and partners" would obscure the four facts that matter.
 */
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 4 }}>{title}</div>
      <div style={{ fontSize: 12.5, color: 'var(--text-secondary)', lineHeight: 1.55 }}>{children}</div>
    </div>
  );
}

export default function PrivacySheet() {
  const { privacyOpen, closePrivacy } = useUI();
  const { session } = useAuth();

  if (!privacyOpen) return null;

  return (
    <Sheet onClose={closePrivacy} label="Privacy">
      <div className="ct-sheet-title">What this app stores</div>

      <Section title="Your library lives in this browser">
        Shows, characters, notes, photos and relationship maps are saved in this browser&rsquo;s
        storage. Clearing your browser data erases them. Nothing here requires an account.
      </Section>

      <Section title={session ? 'Your account holds a copy' : 'If you sign in'}>
        {session ? <>Signed in as <strong style={{ color: 'var(--text)' }}>{session.email}</strong>. Your</> : 'Your'}{' '}
        email address and the records you&rsquo;ve written are stored on Supabase, on servers in the
        United States, so they can reach your other devices. Cast loaded automatically from TMDb is
        not uploaded — it regenerates anywhere. There is no password; signing in is a code sent to
        your email.
      </Section>

      <Section title="What goes to other services">
        Show searches, cast lists and episode data come from <strong style={{ color: 'var(--text)' }}>TMDb</strong>,
        and in-character images from <strong style={{ color: 'var(--text)' }}>TVmaze</strong>. Both are
        requested by this app&rsquo;s own server rather than by your browser, so neither sees who is
        asking. Character bios are generated by sending a show title and a character name — both
        from TMDb — to <strong style={{ color: 'var(--text)' }}>Wikipedia</strong> and{' '}
        <strong style={{ color: 'var(--text)' }}>Anthropic</strong>, and the result is cached so the
        same character is only generated once.{' '}
        <strong style={{ color: 'var(--text)' }}>What you write is never sent to any of them.</strong>
      </Section>

      <Section title="Share links carry their own contents">
        A share link holds the show and characters inside the link itself, after the{' '}
        <code style={{ fontSize: 11.5 }}>#</code>. Browsers never send that part to a server, so what
        you share goes only to the person you send it to — not through this app, and not through
        whoever delivers the message.
      </Section>

      <Section title="Feedback">
        The feedback form sends whatever you type, plus the name and email you put in it, to
        Formspree, which forwards it by email. Leave those blank if you&rsquo;d rather not be
        identifiable.
      </Section>

      <Section title="No tracking">
        No analytics, no advertising, no third-party trackers, no cookies beyond the sign-in session.
        Nothing here is sold or shared with anyone.
      </Section>

      <Section title="Removing it">
        Settings offers two things: clearing this device, which leaves your account untouched, and
        deleting your library everywhere, which removes it from the server and every device. Sign-in
        emails and hosting logs are held briefly by Resend and Vercel in the ordinary course of
        delivering them.
      </Section>

      <button onClick={closePrivacy} className="ct-btn-ghost" style={{ width: '100%', marginTop: 4 }}>Done</button>
    </Sheet>
  );
}
